### ISSUE TITLE
unable to add more options on safari

### ISSUE THREAD

**Issue by robjtede** [srph/gh-polls-web#1]
Neither clicking "Add new option" nor tabbing creates a new option.

Seems to be Safari only, I tried in Chrome and Firefox. No errors in console.

**Comment by srph** [comment]
This seems to be a tabbing issue with Safari. I don't have access to my macs right now, but this [Stack Overflow](https://stackoverflow.com/questions/29104596/add-tabindex-focus-to-buttons-in-safari-without-changing-default-browser-prefe) question mentions a fix by enabling a specific preference.

Thanks!

I think this should be fixed by simply changing event listeners. Currently, the "add option" button is using the `focus` event.

**Comment by robjtede** [comment]
I can confirm that Option-Tab is able to add new options as that SO answer seems to suggest.

**Comment by srph** [comment]
Should be possible now - except for the tabbing convenience.

Feel free to open up an issue if it's annoying to use the tool with Safari.
